### ISSUE TITLE
auto update should be removed.

### ISSUE THREAD

**Issue by Thadir** [NotCapengeR/ShowHiddenChannelsReturns#1]
REmove  * @updateUrl https://mwittrien.github.io/BetterDiscordAddons/Plugins/ShowHiddenChannels/ShowHiddenChannels.plugin.js from the js or it will auto update and delte.

**Comment by NotCapengeR** [comment]
> REmove * @updateUrl https://mwittrien.github.io/BetterDiscordAddons/Plugins/ShowHiddenChannels/ShowHiddenChannels.plugin.js from the js or it will auto update and delte.
It won't auto update. 'cuz that path is actually invalid for this plugin (if you click this URL it will response you an error 404 lol). Author moved it to: https://github.com/mwittrien/BetterDiscordAddons/blob/master/_DEAD/ShowHiddenChannels.plugin.js

**Comment by RobinRMC** [comment]
I can confirm that the plugin auto-updates.

**Comment by RobinRMC** [comment]
I have changed the version to 9.9.9 for myself.

**Comment by NotCapengeR** [comment]
This is because plugin get update URL from the original 0BDFD8.data.json file. Use a patched file that can't provide it
