### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by YorikoMatsumi** [NotCapengeR/ShowHiddenChannelsReturns#10]
Hello^^ I tried using this plugin.. It downloaded the library plugin too. Somehow it didn't show the hidden channels in my private discord. Is there any important step that I missed? I downloaded the plugin and put it in the plugin folder and turned it on. Didn't work. Please let me know any updates on this issue :)

**Comment by NotCapengeR** [comment]
Do not download library plugin from here. Also there is a bug, when plugin doesn't show hidden channels — you ca fix it just pressing Ctrl+R

**Comment by MrMcEpic** [comment]
> Do not download library plugin from here. Also there is a bug, when plugin doesn't show hidden channels — you can fix it with just press Ctrl+R
Where should we download it from then?

**Comment by NotCapengeR** [comment]
Use the original library plugin

**Comment by ShazamCS** [comment]
> Do not download library plugin from here. Also there is a bug, when plugin doesn't show hidden channels — you can fix it with just press Ctrl+R

I did download it from here while better discord deleted the original plugin from my files. It works completely fine I hope this won't get removed aswell. Thanks for remaking it.

**Comment by Cbrooks99** [comment]
It worked perfectly for me .. you have to download it as Zip, then in
Better Discord add the .json file and the .js file to your Plugins folder.
Once you do that you can Ctrl+R to reload your discord and it should be
working again.. after you enable it in plugins.

**Comment by YorikoMatsumi** [comment]
thank you all, it worked after I pressed CTRL + R  <3
