### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by AprentiUnity** [NotCapengeR/ShowHiddenChannelsReturns#11]
I did the installation as indicated, but the plugin does not work. I installed the plugin and the BDFDB library in the latest version. However, I don't see any hidden rooms.
Can anyone help me?

**Comment by NotCapengeR** [comment]
Have you tried to press Ctrl+R?

**Comment by AprentiUnity** [comment]
Yes

**Comment by AprentiUnity** [comment]
In the end, doing the whole installation again, it works. I didn't understand why it didn't work before.
