### ISSUE TITLE
I can't get the plugin to work properly 

### ISSUE THREAD

**Issue by coziestz** [NotCapengeR/ShowHiddenChannelsReturns#12]
how exactly do I use this plugin? I assume I just drag both files included in the download into the plugins folder, but it's not working and I'm not sure what I'm doing wrong.

**Comment by NotCapengeR** [comment]
This plugin is not work without refresh. Try to press Ctrl+R when plugin enable

**Comment by coziestz** [comment]
still not working

**Comment by NotCapengeR** [comment]
So, do you use the latest 0BDFDB library version?

**Comment by Mcbuzzerr** [comment]
I refreshed and checked that have the newest version of the 0BDFDB library and it isn't working for me either

**Comment by Bombshell2** [comment]
Same issue here. Tried both the latest build of 0BDFDB and one before the removal of ShowHiddenChannels, none worked.

**Comment by JustOptimize** [comment]
ProcessChannelList() doesn't work as ProcessChannels() that's why I use a custom library to bring back that missing feature.
