### ISSUE TITLE
Not starting up consistently

### ISSUE THREAD

**Issue by TheMargwa** [NotCapengeR/ShowHiddenChannelsReturns#13]
Everytime I start discord every plugin loads except this one. You would have to go into your plugin library and hit reload for it to start.

**Comment by NotCapengeR** [comment]
The problem in a 0BDFDB library. And I cannot fix it without modified it. But you may try to use another plugins like [https://github.com/Tharki-God/BetterDiscordPlugins/blob/master/ShowHiddenChannels.plugin.js](this)

**Comment by NotCapengeR** [comment]
You can also just press Ctrl+R after every starts of Discord.

**Comment by TheMargwa** [comment]
tysm for all
