### ISSUE TITLE
not working after new update

### ISSUE THREAD

**Issue by XHesaX** [NotCapengeR/ShowHiddenChannelsReturns#15]
the plugin is not working anymore

**Comment by NotCapengeR** [comment]
I know. Last Discord update broke almost all of BetterDiscord plugins [14](https://github.com/NotCapengeR/ShowHiddenChannelsReturns/issues/14). Just wait for fix from Better Discord plugin developers

**Comment by rom4ster** [comment]
They are claiming that all plugins will need to be re written so...
