### ISSUE TITLE
Metadata @source and @updateUrl refer to non-existant files in this repo

### ISSUE THREAD

**Issue by XDelta** [NotCapengeR/ShowHiddenChannelsReturns#17]
https://github.com/NotCapengeR/ShowHiddenChannelsReturns/blob/master/ShowHiddenChannelsReturns.plugin.js#L11-L12

**Comment by NotCapengeR** [comment]
Bruh, forget to rename 😧

**Comment by WCRaptor** [comment]
Still does not work for me

**Comment by XDelta** [comment]
This wouldn't fix the current issue #14 with discord changes breaking plugins, Also would be waiting on potentially more changes on BDFDB. This is just breaking the update checker for this plugin so you can auto-update it from BD
