### ISSUE TITLE
how to update README.md

### ISSUE THREAD

**Issue by Tondaztratilbonga** [NotCapengeR/ShowHiddenChannelsReturns#18]

**Comment by NotCapengeR** [comment]
?

**Comment by Tondaztratilbonga** [comment]
![image](https://user-images.githubusercontent.com/114881447/193666897-8372bdbc-5079-4d85-ac6a-2205c68d8daf.png)
i dont know ehat to do with this

**Comment by VisionsHz** [comment]
you made the post...

**Comment by NotCapengeR** [comment]
> ![image](https://user-images.githubusercontent.com/114881447/193666897-8372bdbc-5079-4d85-ac6a-2205c68d8daf.png) 
i dont know what to do with this @NotCapengeR

Nothing...
