### ISSUE TITLE
Not working with new update.

### ISSUE THREAD

**Issue by BySwiizen** [NotCapengeR/ShowHiddenChannelsReturns#19]
Hi, even after updating the 0BDFDB library the plugin still does not work, there will be a plugin update soon?

**Comment by Euron-CE** [comment]
Yeah nothing I try will get it to work either.

**Comment by Pyruswon** [comment]
I'm sure its an easy fix and they'll get around to it -- best not to pressure the dev(s) :P

**Comment by BySwiizen** [comment]
Up?
