### ISSUE TITLE
For those Everyone who are Expecting this Plugin to get fixed

### ISSUE THREAD

**Issue by FASTANDEXTREME** [NotCapengeR/ShowHiddenChannelsReturns#20]
ShowHiddenChannels has hit EOL [End of Life]. This means this plugin is no longer updated or maintained. This plugin is against TOS of BetterDiscord and hence, shall be not present on their website. Therefore, there is little to no chance of this plugin getting fixed unless some other developer fixes it and updates it on github or similar platforms. Plugins downloaded from other sources are harmful and may lead to hijack/suspension of your Discord Account. 

Edit: Even Updating BDFDB will not fix the issue, as the issue is in plugin itself and not the library.

**Comment by lynrayy** [comment]
Dude, the plugin is handled by another person, of course it will work again sooner or later

**Comment by FASTANDEXTREME** [comment]
If it is handled, its good. But there are nearly 0 chances that Original author DevilBro will work on it. Also Plugins from not well known github links can hijack your account and what not.

**Comment by NotCapengeR** [comment]
Are plugins are just JS-files, so if there is a function which can steal tokens or another user info, it will be visible in the source code. :D

**Comment by makemedie** [comment]
> Dude, the plugin is handled by another person, of course it will work again sooner or later

do you know people who are working on a fix?

**Comment by Vercalos** [comment]
> Are plugins are just JS-files, so if there is a function which can steal tokens or another user info, it will be visible in the source code. :D

Well, yeah, but how many end-users of these plugins understand Javascript enough to recognize the code to acquire information the end-user doesn't want shared?

**Comment by Bulkin777** [comment]
Brothers, is someone working on fixing this plugin?

**Comment by NotCapengeR** [comment]
> Brothers, is someone working on fixing this plugin?

Nope

**Comment by Bulkin777** [comment]
> > Братья, кто-нибудь работает над исправлением этого плагина?
> 
> Нет

Sadly

**Comment by Bulkin777** [comment]
Is it even possible to fix it? I'm just weak in programming, it's just that this plugin is very cool

**Comment by NotCapengeR** [comment]
> Is it even possible to fix it? I'm just weak in programming, it's just that this plugin is very cool

Ofc it is. OBDFD8 is currently fixed. So, SHC can be fixed too, but I can't do this

**Comment by steaksfrite** [comment]
@NotCapengeR  can you contact DevilBro and ask him to update his plugin? I'm not a dev I don't know anything about it but it's the best discord plugin we all have to do to make it come back :)

**Comment by Bulkin777** [comment]
> @NotCapengeR не могли бы вы связаться с DevilBro и попросить его обновить свой плагин? Я не разработчик, я ничего об этом не знаю, но это лучший плагин discord, который мы все должны сделать, чтобы он вернулся :)

Alas, but DevilBro will not update this plugin, or return it somehow, because he himself refused this plugin, so the only hope is for others who can make a fix.

**Comment by FASTANDEXTREME** [comment]
Yes, Learn to Code and fix it, or wait for someone else to fix it and release them.

**Comment by Bulkin777** [comment]
> Yes, Learn to Code and fix it, or wait for someone else to fix it and release them.

Javascript is not easy to learn as far as I know, if you start right from 0, it's obviously faster for someone to fix it and release it :D

**Comment by NotCapengeR** [comment]
Just Optimize is gonna [work](https://github.com/JustOptimize/return-ShowHiddenChannels) on this plugin. His version is worked now, but has some bugs. So, I probably archive this repository if he make his own plugin

**Comment by alucardontop** [comment]
> Just Optimize is gonna [work](https://github.com/JustOptimize/return-ShowHiddenChannels) on this plugin. His version is worked now, but has some bugs. So, I probably archive this repository if he make his own plugin

his plugin works, thank you
