### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Giveup911** [NotCapengeR/ShowHiddenChannelsReturns#3]
when i download it and replace and delete what you said to do it still gets updated and deleted

**Comment by Giveup911** [comment]
![image_2022-09-05_201951963](https://user-images.githubusercontent.com/109944484/188523037-9571ba01-5599-4920-b493-3fff34555d85.png)

**Comment by NotCapengeR** [comment]
It shouldn't be updated, because updateUrl is invalid. Try to manually replace it or version number 
![Screenshot_2022-09-06-06-58-20-331_com.github.android.jpg](https://user-images.githubusercontent.com/90960831/188531255-39365773-02ab- -4165-85ce-e17ba0ea6e51.jpg)

**Comment by Volas171** [comment]
> It shouldn't be updated, because updateUrl is invalid. Try to manually replace it or version number on top of the file.

updateUrl is actually valid (cache) so you might want to change that to `https://github.com/NotCapengeR/ShowHiddenChannelsReturns/blob/master/ShowHiddenChannels.plugin.js` anyways

**Comment by NotCapengeR** [comment]
> this is worthless anyways, in 24 hours or less they are going to release a patch for it

They gonna remove some library functions for plugin work? Ok. then I'll add it manually! 

I've also changed update URL.

**Comment by Giveup911** [comment]
its still not working

**Comment by NotCapengeR** [comment]
It's could be problem with your BDFD8 plugin. Have you tried to change version number to 9.9.9?

**Comment by NotCapengeR** [comment]
And can you please send me your 0BDFDB.data.json file?

**Comment by Giveup911** [comment]
It's 12 am for me I'm going to bed

**Comment by NotCapengeR** [comment]
Goodnight 😊😘

**Comment by xiaodeng52** [comment]
I think 0BDFDB library is not working properly with your version of older show hidden channel js. Maybe you can try fix that. This plugin is not working rn

**Comment by anoymcat** [comment]
I think 0BDFDB.data.json is not supporting your uploaded version of showhiddenchannel. Maybe you can work on that. I ve upload the original library files for your reference!!
[0BDFDB.zip](https://github.com/NotCapengeR/ShowHiddenChannelsReturns/files/9493283/0BDFDB.zip)

**Comment by anoymcat** [comment]
I did not encounter problems of auto updates but the plugin just wont work even after sign of loading successfully.

**Comment by BokChoy-tech** [comment]
Mine as well auto-updates every time I add it to the plugin folder.

**Comment by NotCapengeR** [comment]
I think, the cause is that original data file contains link on broken by DevilBro plugin. Try to change version to 9.9.9 before putting

**Comment by NotCapengeR** [comment]
I'm gonna to fix it soo6, just wait

**Comment by NotCapengeR** [comment]
If you still have problems with this plugin, open this issue again
