### ISSUE TITLE
(Suggestion) Mark the files as Read Only.

### ISSUE THREAD

**Issue by BlueWolfKenji** [NotCapengeR/ShowHiddenChannelsReturns#5]
Better discord still changes those files back to being useless anyway. 

The way to fix this is to mark both OBDFDB.data.json and ShowHiddenChannels.plugin.js as READ ONLY. 

This might be temporal, but it prevents better discord to update it, therefore, not prompting the user to delete it, loading it happily.

**Comment by NotCapengeR** [comment]
Preventing auto-updates of 0BDFDB.data.json might broken another plugins. Or you should manually add required lines for its work as needed

**Comment by NotCapengeR** [comment]
Auto-updates are actually fixed. You no more need to replace 0BDFDB.data.json file
