### ISSUE TITLE
will not work

### ISSUE THREAD

**Issue by nlmetal** [NotCapengeR/ShowHiddenChannelsReturns#6]
i followed steps - downloaded .js file, dropped it into the plugins folder, relaunched discord. 

am i missing something?

**Comment by NotCapengeR** [comment]
Not working? Auto-updating?

**Comment by NotCapengeR** [comment]
Or you enable this plugin and it just not work?

**Comment by nlmetal** [comment]
i just add it and it doesnt work - im not sure what is wrong :(

**Comment by NotCapengeR** [comment]
Maybe you forget to enable it? :D 
![изображение](https://user-images.githubusercontent.com/90960831/188870073-b96574dd-8087-4e5a-a0e1-50ed2a7b2630.png)

**Comment by nlmetal** [comment]
i am quite literally brain dead.

this fixed it. thank you.
