### ISSUE TITLE
Currently not working.

### ISSUE THREAD

**Issue by MachineGalaxy** [NotCapengeR/ShowHiddenChannelsReturns#7]
I downloaded both the released version and the .js files in the master, but neither has worked. 
I've tried both with Discord open and closed. I also tried reloading. 
The plugin says it loaded correctly and is enabled, but it doesn't appear to show the hidden channels.

**Comment by NotCapengeR** [comment]
It seems to missing required version of 0BDFDB version and 0BDFDB.data.json file. Update them or download manually: 
https://github.com/mwittrien/BetterDiscordAddons/blob/master/Library/_res/0BDFDB.data.json

**Comment by MachineGalaxy** [comment]
Hmm, even after downloading the library, it still isn't working. BetterDiscord is saying 0BDFDB is no longer up to date though.

**Comment by NotCapengeR** [comment]
Could you send a screenshot?

**Comment by NotCapengeR** [comment]
Try to press button to update BDFDB plugin on top

**Comment by MachineGalaxy** [comment]
Ok, I kinda got it to work. If you disable it and enable it, it works until discord is restarted. 
It's happening on both the old version of 0BDFDB and the one it wants to update to.

**Comment by NotCapengeR** [comment]
Oof, I have the same problem with 0BDFDB.data.json file
